# Generated by Django 4.2 on 2023-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderreg',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
