# Generated by Django 4.2 on 2023-05-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_alter_tenderreg_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderreg',
            name='tender_status',
        ),
        migrations.RemoveField(
            model_name='tenderreg',
            name='winner',
        ),
    ]
