# Generated by Django 4.2 on 2023-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_remove_tenderreg_tender_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderRequireiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqname', models.CharField(max_length=200)),
            ],
        ),
    ]
