# Generated by Django 4.2 on 2023-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_tenderrequireiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqireList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inputs', models.ManyToManyField(to='tender.tenderrequireiment')),
            ],
        ),
    ]
