# Generated by Django 4.2 on 2023-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_alter_reqirelist_rqired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqirelist',
            name='inputs',
        ),
        migrations.AlterField(
            model_name='reqirelist',
            name='rqired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reqirelist',
            name='inputs',
            field=models.CharField(default=2152023, max_length=2500),
            preserve_default=False,
        ),
    ]
