# Generated by Django 4.2 on 2023-05-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0009_reqired_vendorcapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqiredContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReqiredInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clentinputs', models.CharField(max_length=2500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.reqiredcontent')),
            ],
        ),
        migrations.CreateModel(
            name='VendorInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorinputs', models.CharField(max_length=2500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.reqiredcontent')),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorcapacity',
            name='name',
        ),
        migrations.DeleteModel(
            name='Reqired',
        ),
        migrations.DeleteModel(
            name='vendorCapacity',
        ),
    ]
