# Generated by Django 4.2 on 2023-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_alter_reqiredinput_clentinputs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReqireList',
        ),
        migrations.RemoveField(
            model_name='tendercond',
            name='condName',
        ),
        migrations.DeleteModel(
            name='TenderRequireiment',
        ),
        migrations.DeleteModel(
            name='TenderCond',
        ),
    ]
