# Generated by Django 4.2 on 2023-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procoficer', '0001_initial'),
        ('tender', '0012_delete_reqirelist_remove_tendercond_condname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderreg',
            name='cliendName',
            field=models.ForeignKey(default=2152023, on_delete=django.db.models.deletion.CASCADE, to='procoficer.clientdetail'),
            preserve_default=False,
        ),
    ]
