# Generated by Django 4.2 on 2023-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_tenderreg_cliendname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderreg',
            name='category',
            field=models.CharField(choices=[('Goods And Services', 'Evaluated'), ('Air Condition Service', 'Air Condition Service'), ('Cleaning Sanitation ', 'Cleaning Sanitation '), ('Construction Buildings', 'Construction Buildings'), ('Construction Buildings', 'Construction Buildings'), ('Ict Internet Telecom ', 'Ict Internet Telecom '), ('Motor Vehicles And Fuel', 'Motor Vehicles And Fuel'), ('Printing And Stationeries ', 'Printing And Stationeries ')], max_length=255),
        ),
    ]
