# Generated by Django 4.2 on 2023-05-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_alter_tenderreg_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenderreg',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.category'),
        ),
    ]
