# Generated by Django 4.2 on 2023-05-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procoficer', '0002_condition_firstmodel_requirement_secondmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondmodel',
            name='first_model',
        ),
        migrations.DeleteModel(
            name='FirstModel',
        ),
        migrations.DeleteModel(
            name='SecondModel',
        ),
    ]
