# Generated by Django 4.2 on 2023-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procoficer', '0003_remove_secondmodel_first_model_delete_firstmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='conditionseted',
            field=models.OneToOneField(default=2852023, on_delete=django.db.models.deletion.CASCADE, to='procoficer.condition'),
            preserve_default=False,
        ),
    ]
